version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_mongo_data: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: pro_bit_task_django
    container_name: pro_bit_task_django
    depends_on:
      - postgres
    volumes:
      - .:/app:cached
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: pro_bit_task_postgres
    container_name: pro_bit_task_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:cached
      - local_postgres_data_backups:/backups:cached
    env_file:
      - ./.envs/.local/.postgres
  